server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
zuul:
  SendErrorFilter:
    post:
      disable: true
  ignoredServices: '*'
  ignoredPatterns: '/api/v1/*/internal/**'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    user: /api/v1/user/**
    post: /api/v1/post/**
    subscription: /api/v1/subscription/**
    auth: /api/v1/auth/**


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
          timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000